server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db.enmsffabzuybtiaiysus.supabase.co:5432/postgres
    username: postgres
    password: 226C1A0544
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      leak-detection-threshold: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true


  devtools:
    restart:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
