server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://dpg-d1f4asre5dus73fhilrg-a.oregon-postgres.render.com/miracle_fest_db
    username: miracle_fest_db_user
    password: gCeXJ6GwpK2pS8X0BbbQBuWSVT23X30t
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      leak-detection-threshold: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
